### ISSUE TITLE
Create SQL script to populate the DataWarehouse

### ISSUE THREAD

**Issue by caiormt** [rschio/sad#9]
After all datasets normalized, we need to batch insert into the DW.

The complication here is how to insert them and link together.
- How to build the keys?
- How to insert them using a single script?
- How to defined the constraints?

**Comment by caiormt** [comment]
Initial structure defined in #11.
Modeled each dimension having its unique ID (probably auto generated by script).

We still need to know how to properly define a key to model it right.

**Comment by rschio** [comment]
In crime database some year have no days, only year and month, should we define TEMPORAL table with possible NULL day and/or weekday?

**Comment by caiormt** [comment]
> In crime database some year have no days, only year and month, should we define TEMPORAL table with possible NULL day and/or weekday?

Fixed.

**Comment by caiormt** [comment]
> Initial structure defined in #11.
> Modeled each dimension having its unique ID (probably auto generated by script).
> 
> We still need to know how to properly define a key to model it right.

Modeled keys as bigserial as indicated by Bruno.
Reference at https://rafaelpiton.com.br/blog/data-warehouse-surrogate-key/

**Comment by caiormt** [comment]
For Accidents and Crimes datasets done in #16.

Awaiting for Homeless datasets to close.
